name: Setup

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Install dependencies
      run: |
        go install go.uber.org/mock/mockgen@latest
      shell: bash

    - name: Go Mod
      run: go mod download
      shell: bash 