// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/go-wallet-sdk/pkg/balance/fetcher (interfaces: RPCClient,BatchCaller,BalanceScanner)
//
// Generated by this command:
//
//	mockgen -destination=mock/fetcher.go . RPCClient,BatchCaller,BalanceScanner
//

// Package mock_fetcher is a generated GoMock package.
package mock_fetcher

import (
	context "context"
	big "math/big"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"
	rpc "github.com/ethereum/go-ethereum/rpc"
	balancescanner "github.com/status-im/go-wallet-sdk/pkg/contracts/balancescanner"
	gomock "go.uber.org/mock/gomock"
)

// MockRPCClient is a mock of RPCClient interface.
type MockRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockRPCClientMockRecorder
	isgomock struct{}
}

// MockRPCClientMockRecorder is the mock recorder for MockRPCClient.
type MockRPCClientMockRecorder struct {
	mock *MockRPCClient
}

// NewMockRPCClient creates a new mock instance.
func NewMockRPCClient(ctrl *gomock.Controller) *MockRPCClient {
	mock := &MockRPCClient{ctrl: ctrl}
	mock.recorder = &MockRPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCClient) EXPECT() *MockRPCClientMockRecorder {
	return m.recorder
}

// BatchCallContext mocks base method.
func (m *MockRPCClient) BatchCallContext(ctx context.Context, b []rpc.BatchElem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCallContext", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCallContext indicates an expected call of BatchCallContext.
func (mr *MockRPCClientMockRecorder) BatchCallContext(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCallContext", reflect.TypeOf((*MockRPCClient)(nil).BatchCallContext), ctx, b)
}

// CallContract mocks base method.
func (m *MockRPCClient) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallContract", ctx, call, blockNumber)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallContract indicates an expected call of CallContract.
func (mr *MockRPCClientMockRecorder) CallContract(ctx, call, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallContract", reflect.TypeOf((*MockRPCClient)(nil).CallContract), ctx, call, blockNumber)
}

// ChainID mocks base method.
func (m *MockRPCClient) ChainID(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChainID indicates an expected call of ChainID.
func (mr *MockRPCClientMockRecorder) ChainID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockRPCClient)(nil).ChainID), ctx)
}

// CodeAt mocks base method.
func (m *MockRPCClient) CodeAt(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodeAt", ctx, contract, blockNumber)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CodeAt indicates an expected call of CodeAt.
func (mr *MockRPCClientMockRecorder) CodeAt(ctx, contract, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodeAt", reflect.TypeOf((*MockRPCClient)(nil).CodeAt), ctx, contract, blockNumber)
}

// MockBatchCaller is a mock of BatchCaller interface.
type MockBatchCaller struct {
	ctrl     *gomock.Controller
	recorder *MockBatchCallerMockRecorder
	isgomock struct{}
}

// MockBatchCallerMockRecorder is the mock recorder for MockBatchCaller.
type MockBatchCallerMockRecorder struct {
	mock *MockBatchCaller
}

// NewMockBatchCaller creates a new mock instance.
func NewMockBatchCaller(ctrl *gomock.Controller) *MockBatchCaller {
	mock := &MockBatchCaller{ctrl: ctrl}
	mock.recorder = &MockBatchCallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchCaller) EXPECT() *MockBatchCallerMockRecorder {
	return m.recorder
}

// BatchCallContext mocks base method.
func (m *MockBatchCaller) BatchCallContext(ctx context.Context, b []rpc.BatchElem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCallContext", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCallContext indicates an expected call of BatchCallContext.
func (mr *MockBatchCallerMockRecorder) BatchCallContext(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCallContext", reflect.TypeOf((*MockBatchCaller)(nil).BatchCallContext), ctx, b)
}

// MockBalanceScanner is a mock of BalanceScanner interface.
type MockBalanceScanner struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceScannerMockRecorder
	isgomock struct{}
}

// MockBalanceScannerMockRecorder is the mock recorder for MockBalanceScanner.
type MockBalanceScannerMockRecorder struct {
	mock *MockBalanceScanner
}

// NewMockBalanceScanner creates a new mock instance.
func NewMockBalanceScanner(ctrl *gomock.Controller) *MockBalanceScanner {
	mock := &MockBalanceScanner{ctrl: ctrl}
	mock.recorder = &MockBalanceScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceScanner) EXPECT() *MockBalanceScannerMockRecorder {
	return m.recorder
}

// EtherBalances mocks base method.
func (m *MockBalanceScanner) EtherBalances(opts *bind.CallOpts, addresses []common.Address) ([]balancescanner.BalanceScannerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EtherBalances", opts, addresses)
	ret0, _ := ret[0].([]balancescanner.BalanceScannerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EtherBalances indicates an expected call of EtherBalances.
func (mr *MockBalanceScannerMockRecorder) EtherBalances(opts, addresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EtherBalances", reflect.TypeOf((*MockBalanceScanner)(nil).EtherBalances), opts, addresses)
}

// TokenBalances mocks base method.
func (m *MockBalanceScanner) TokenBalances(opts *bind.CallOpts, addresses []common.Address, tokenAddress common.Address) ([]balancescanner.BalanceScannerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenBalances", opts, addresses, tokenAddress)
	ret0, _ := ret[0].([]balancescanner.BalanceScannerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenBalances indicates an expected call of TokenBalances.
func (mr *MockBalanceScannerMockRecorder) TokenBalances(opts, addresses, tokenAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenBalances", reflect.TypeOf((*MockBalanceScanner)(nil).TokenBalances), opts, addresses, tokenAddress)
}

// TokensBalance mocks base method.
func (m *MockBalanceScanner) TokensBalance(opts *bind.CallOpts, owner common.Address, contracts []common.Address) ([]balancescanner.BalanceScannerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokensBalance", opts, owner, contracts)
	ret0, _ := ret[0].([]balancescanner.BalanceScannerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokensBalance indicates an expected call of TokensBalance.
func (mr *MockBalanceScannerMockRecorder) TokensBalance(opts, owner, contracts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokensBalance", reflect.TypeOf((*MockBalanceScanner)(nil).TokensBalance), opts, owner, contracts)
}
