#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>

// Header generated by Go build -buildmode=c-shared
#include "libgowalletsdk.h"

int test_ethclient();
int test_accounts();

// Helper function to extract address from JSON account string
// JSON format: {"address":"0x...","url":"..."}
static char* extract_address_from_json(const char* json) {
    if (json == NULL) return NULL;
    const char* addr_start = strstr(json, "\"address\":\"");
    if (addr_start == NULL) return NULL;
    addr_start += 11; // Skip "address":"
    const char* addr_end = strchr(addr_start, '"');
    if (addr_end == NULL) return NULL;
    size_t len = addr_end - addr_start;
    char* addr = (char*)malloc(len + 1);
    if (addr == NULL) return NULL;
    memcpy(addr, addr_start, len);
    addr[len] = '\0';
    return addr;
}

int main(int argc, char** argv) {
    int result = 0;
    result = test_ethclient();
    if (result != 0) {
        fprintf(stderr, "ethclient failed\n");
        return 1;
    }
    result = test_accounts();
    if (result != 0) {
        fprintf(stderr, "acccounts failed\n");
        return 1;
    }
    return result;
}

int test_ethclient() {
    const char* url = "https://ethereum-rpc.publicnode.com";
    const char* addr = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"; // vitalik.eth

    char* err = NULL;
    unsigned long long h = GoWSK_ethclient_NewClient((char*)url, &err);
    if (h == 0) {
        fprintf(stderr, "Failed to create client: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        return 1;
    }

    char* chain = GoWSK_ethclient_ChainID(h, &err);
    if (chain == NULL) {
        fprintf(stderr, "ChainID error: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_ethclient_CloseClient(h);
        return 1;
    }
    printf("ChainID: %s\n", chain);
    // Parse chain ID before freeing the string
    char* endptr;
    unsigned long chainID = strtoul(chain, &endptr, 0);
    if (*endptr != '\0' || endptr == chain) {
        fprintf(stderr, "Failed to parse chain ID\n");
        GoWSK_FreeCString(chain);
        GoWSK_ethclient_CloseClient(h);
        return 1;
    }
    GoWSK_FreeCString(chain);

    char* balance = GoWSK_ethclient_GetBalance(h, (char*)addr, &err);
    if (balance == NULL) {
        fprintf(stderr, "GetBalance error: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_ethclient_CloseClient(h);
        return 1;
    }
    printf("Balance(wei): %s\n", balance);
    GoWSK_FreeCString(balance);

    char* rpcCallRequest = "{\"method\":\"eth_getBalance\",\"params\":[\"0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045\",\"latest\"]}";
    char* rpcCallResponse = GoWSK_ethclient_RPCCall(h, rpcCallRequest, &err);
    if (rpcCallResponse == NULL) {
        fprintf(stderr, "RPCCall error: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_ethclient_CloseClient(h);
        return 1;
    }
    printf("RPCCall\nRequest: %s\nResponse: %s\n", rpcCallRequest, rpcCallResponse);
    GoWSK_FreeCString(rpcCallResponse);

    // Example: Fetch balances using multistandardfetcher
    printf("\n=== Fetching balances with multistandardfetcher ===\n");
    
    // Create fetch config JSON: native balance + ERC20 tokens + ERC721 NFTs + ERC1155 collectibles
    // ERC20 tokens:
    //   USDC: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
    //   SHIB: 0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE
    // ERC721 NFTs:
    //   Bored Ape Yacht Club: 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D
    //   Pudgy Penguins: 0xbd3531da5cf5857e7cfaa92426877b022e612cf8
    // ERC1155 collectibles (format: "contractAddress:tokenID"):
    //   OpenSea Shared Storefront: 0x495f947276749Ce646f68AC8c248420045cb7b5e:80725417304363601833901294931248829736335313578142415985923215537121414611044
    //   Parallel Alpha: 0x76BE3b62873462d2142405439777e971754E8E77:1
    const char* fetchConfigJSON = 
        "{"
        "\"native\":[\"0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045\"],"
        "\"erc20\":{"
        "\"0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045\":["
        "\"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48\","
        "\"0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE\""
        "]"
        "},"
        "\"erc721\":{"
        "\"0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045\":["
        "\"0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D\","
        "\"0xbd3531da5cf5857e7cfaa92426877b022e612cf8\""
        "]"
        "},"
        "\"erc1155\":{"
        "\"0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045\":["
        "\"0x495f947276749Ce646f68AC8c248420045cb7b5e:80725417304363601833901294931248829736335313578142415985923215537121414611044\","
        "\"0x76BE3b62873462d2142405439777e971754E8E77:1\""
        "]"
        "}"
        "}";
    
    err = NULL;
    unsigned long batchSize = 100;
    char* resultsJSON = GoWSK_balance_multistandardfetcher_FetchBalances(
        (uintptr_t)h, 
        chainID, 
        batchSize, 
        (char*)fetchConfigJSON, 
        &err
    );
    
    if (resultsJSON == NULL) {
        fprintf(stderr, "FetchBalances error: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_ethclient_CloseClient(h);
        return 1;
    }
    
    printf("FetchBalances Results:\n%s\n", resultsJSON);
    GoWSK_FreeCString(resultsJSON);

    GoWSK_ethclient_CloseClient(h);
    return 0;
}

int test_accounts() {
    printf("\n=== Testing Accounts ===\n");
    char* err = NULL;
    
    // Test 1: Create a mnemonic
    printf("\n1. Creating mnemonic...\n");
    err = NULL;
    char* mnemonic = GoWSK_accounts_mnemonic_CreateRandomMnemonicWithDefaultLength(&err);
    if (mnemonic == NULL) {
        fprintf(stderr, "Failed to create mnemonic: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        return 1;
    }
    printf("Mnemonic: %s\n", mnemonic);
    
    // Test 2: Create extended key from mnemonic
    printf("\n2. Creating extended key from mnemonic...\n");
    err = NULL;
    char* extKeyStr = GoWSK_accounts_keys_CreateExtKeyFromMnemonic(mnemonic, NULL, &err);
    if (extKeyStr == NULL) {
        fprintf(stderr, "Failed to create extended key: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_FreeCString(mnemonic);
        return 1;
    }
    printf("Extended Key: %s\n", extKeyStr);
    
    // Test 3: Derive a child key
    printf("\n3. Deriving child key...\n");
    const char* derivationPath = "m/44'/60'/0'/0/0";
    err = NULL;
    char* derivedKeyStr = GoWSK_accounts_keys_DeriveExtKey(extKeyStr, (char*)derivationPath, &err);
    if (derivedKeyStr == NULL) {
        fprintf(stderr, "Failed to derive key: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        return 1;
    }
    printf("Derived Key: %s\n", derivedKeyStr);
    
    // Test 4: Get ECDSA private key from extended key
    printf("\n4. Converting extended key to ECDSA...\n");
    err = NULL;
    char* privateKeyHex = GoWSK_accounts_keys_ExtKeyToECDSA(derivedKeyStr, &err);
    if (privateKeyHex == NULL) {
        fprintf(stderr, "Failed to convert to ECDSA: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        return 1;
    }
    printf("Private Key: %s\n", privateKeyHex);
    
    // Test 5: Get address from public key
    printf("\n5. Getting address from public key...\n");
    err = NULL;
    char* publicKeyHex = GoWSK_accounts_keys_ECDSAToPublicKey(privateKeyHex, &err);
    if (publicKeyHex == NULL) {
        fprintf(stderr, "Failed to get public key: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        return 1;
    }
    err = NULL;
    char* address = GoWSK_accounts_keys_PublicKeyToAddress(publicKeyHex, &err);
    if (address == NULL) {
        fprintf(stderr, "Failed to get address: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(publicKeyHex);
        return 1;
    }
    printf("Address: %s\n", address);
    GoWSK_FreeCString(publicKeyHex);
    
    // Test 6: Create keystore and extkeystore
    printf("\n6. Creating keystores...\n");
    // Generate unique directory names using timestamp
    time_t now = time(NULL);
    char keystoreDir[256];
    char extkeystoreDir[256];
    snprintf(keystoreDir, sizeof(keystoreDir), "/tmp/test_keystore_%ld", now);
    snprintf(extkeystoreDir, sizeof(extkeystoreDir), "/tmp/test_extkeystore_%ld", now);
    printf("Keystore directory: %s\n", keystoreDir);
    printf("ExtKeystore directory: %s\n", extkeystoreDir);
    // Use light scrypt for faster testing (LightScryptN = 4096, LightScryptP = 6)
    int scryptN = 4096;
    int scryptP = 6;
    
    err = NULL;
    unsigned long long ksHandle = GoWSK_accounts_keystore_NewKeyStore(keystoreDir, scryptN, scryptP, &err);
    if (ksHandle == 0) {
        fprintf(stderr, "Failed to create keystore: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(address);
        return 1;
    }
    printf("Keystore created\n");
    
    err = NULL;
    unsigned long long extKsHandle = GoWSK_accounts_extkeystore_NewKeyStore(extkeystoreDir, scryptN, scryptP, &err);
    if (extKsHandle == 0) {
        fprintf(stderr, "Failed to create extkeystore: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_accounts_keystore_CloseKeyStore(ksHandle);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(address);
        return 1;
    }
    printf("ExtKeystore created\n");
    
    // Test 7: Create new accounts in both keystores
    printf("\n7. Creating new accounts...\n");
    const char* passphrase = "test123";
    
    err = NULL; // Reset error pointer
    char* ksAccount1JSON = GoWSK_accounts_keystore_NewAccount(ksHandle, (char*)passphrase, &err);
    if (ksAccount1JSON == NULL) {
        fprintf(stderr, "Failed to create account in keystore: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_accounts_keystore_CloseKeyStore(ksHandle);
        GoWSK_accounts_extkeystore_CloseKeyStore(extKsHandle);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(address);
        return 1;
    }
    printf("Keystore Account 1: %s\n", ksAccount1JSON);
    
    err = NULL; // Reset error pointer
    char* extKsAccount1JSON = GoWSK_accounts_extkeystore_NewAccount(extKsHandle, (char*)passphrase, &err);
    if (extKsAccount1JSON == NULL) {
        fprintf(stderr, "Failed to create account in extkeystore: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_FreeCString(ksAccount1JSON);
        GoWSK_accounts_keystore_CloseKeyStore(ksHandle);
        GoWSK_accounts_extkeystore_CloseKeyStore(extKsHandle);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(address);
        return 1;
    }
    printf("ExtKeystore Account 1: %s\n", extKsAccount1JSON);
    
    // Test 8: Import ECDSA private key into keystore
    printf("\n8. Importing ECDSA private key into keystore...\n");
    err = NULL; // Reset error pointer
    char* ksAccount2JSON = GoWSK_accounts_keystore_ImportECDSA(ksHandle, privateKeyHex, (char*)passphrase, &err);
    if (ksAccount2JSON == NULL) {
        fprintf(stderr, "Failed to import ECDSA key into keystore: %s\n", err ? err : "unknown error");
        if (err) {
            GoWSK_FreeCString(err);
            err = NULL;
        }
        GoWSK_FreeCString(ksAccount1JSON);
        GoWSK_FreeCString(extKsAccount1JSON);
        GoWSK_accounts_keystore_CloseKeyStore(ksHandle);
        GoWSK_accounts_extkeystore_CloseKeyStore(extKsHandle);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(address);
        return 1;
    }
    printf("Keystore Account 2 (imported): %s\n", ksAccount2JSON);
    
    // Extract address from imported account for later use
    char* importedAddress = extract_address_from_json(ksAccount2JSON);
    if (importedAddress == NULL) {
        fprintf(stderr, "Failed to extract address from imported account JSON\n");
        GoWSK_FreeCString(ksAccount1JSON);
        GoWSK_FreeCString(extKsAccount1JSON);
        GoWSK_FreeCString(ksAccount2JSON);
        GoWSK_accounts_keystore_CloseKeyStore(ksHandle);
        GoWSK_accounts_extkeystore_CloseKeyStore(extKsHandle);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(address);
        return 1;
    }
    printf("Imported account address: %s\n", importedAddress);
    
    // Test 9: Import extended key into extkeystore
    printf("\n9. Importing extended key into extkeystore...\n");
    err = NULL; // Reset error pointer
    char* extKsAccount2JSON = GoWSK_accounts_extkeystore_ImportExtendedKey(extKsHandle, extKeyStr, (char*)passphrase, &err);
    if (extKsAccount2JSON == NULL) {
        fprintf(stderr, "Failed to import extended key into extkeystore: %s\n", err ? err : "unknown error");
        if (err) {
            GoWSK_FreeCString(err);
            err = NULL;
        }
        free(importedAddress);
        GoWSK_FreeCString(ksAccount1JSON);
        GoWSK_FreeCString(extKsAccount1JSON);
        GoWSK_FreeCString(ksAccount2JSON);
        GoWSK_accounts_keystore_CloseKeyStore(ksHandle);
        GoWSK_accounts_extkeystore_CloseKeyStore(extKsHandle);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(address);
        return 1;
    }
    printf("ExtKeystore Account 2 (imported): %s\n", extKsAccount2JSON);
    
    // Extract address from extkeystore imported account for later use
    char* extImportedAddress = extract_address_from_json(extKsAccount2JSON);
    if (extImportedAddress == NULL) {
        fprintf(stderr, "Failed to extract address from extkeystore imported account JSON\n");
        free(importedAddress);
        GoWSK_FreeCString(ksAccount1JSON);
        GoWSK_FreeCString(extKsAccount1JSON);
        GoWSK_FreeCString(ksAccount2JSON);
        GoWSK_FreeCString(extKsAccount2JSON);
        GoWSK_accounts_keystore_CloseKeyStore(ksHandle);
        GoWSK_accounts_extkeystore_CloseKeyStore(extKsHandle);
        GoWSK_FreeCString(mnemonic);
        GoWSK_FreeCString(extKeyStr);
        GoWSK_FreeCString(derivedKeyStr);
        GoWSK_FreeCString(privateKeyHex);
        GoWSK_FreeCString(address);
        return 1;
    }
    printf("ExtKeystore imported account address: %s\n", extImportedAddress);
    
    // Test 10: Export from keystore
    printf("\n10. Exporting from keystore...\n");
    const char* newPassphrase = "newpass123";
    err = NULL; // Reset error pointer
    char* exportedKeyJSON = GoWSK_accounts_keystore_Export(ksHandle, importedAddress, (char*)passphrase, (char*)newPassphrase, &err);
    if (exportedKeyJSON == NULL) {
        fprintf(stderr, "Failed to export from keystore: %s\n", err ? err : "unknown error");
        if (err) {
            GoWSK_FreeCString(err);
            err = NULL;
        }
    } else {
        printf("Exported key (first 100 chars): %.100s...\n", exportedKeyJSON);
        GoWSK_FreeCString(exportedKeyJSON);
    }
    
    // Test 11: Export from extkeystore (both formats)
    printf("\n11. Exporting from extkeystore...\n");
    err = NULL; // Reset error pointer
    char* exportedExtKeyJSON = GoWSK_accounts_extkeystore_ExportExt(extKsHandle, extImportedAddress, (char*)passphrase, (char*)newPassphrase, &err);
    if (exportedExtKeyJSON == NULL) {
        fprintf(stderr, "Failed to export extended key: %s\n", err ? err : "unknown error");
        if (err) {
            GoWSK_FreeCString(err);
            err = NULL;
        }
    } else {
        printf("Exported extended key (first 100 chars): %.100s...\n", exportedExtKeyJSON);
        GoWSK_FreeCString(exportedExtKeyJSON);
    }
    
    err = NULL; // Reset error pointer
    char* exportedPrivKeyJSON = GoWSK_accounts_extkeystore_ExportPriv(extKsHandle, extImportedAddress, (char*)passphrase, (char*)newPassphrase, &err);
    if (exportedPrivKeyJSON == NULL) {
        fprintf(stderr, "Failed to export private key: %s\n", err ? err : "unknown error");
        if (err) {
            GoWSK_FreeCString(err);
            err = NULL;
        }
    } else {
        printf("Exported private key (first 100 chars): %.100s...\n", exportedPrivKeyJSON);
        // Keep exportedPrivKeyJSON for import test below
    }
    
    // Test 12: Import exported private key from extkeystore into keystore
    printf("\n12. Importing exported private key from extkeystore into keystore...\n");
    if (exportedPrivKeyJSON != NULL) {
        err = NULL; // Reset error pointer
        char* importedFromExtKsJSON = GoWSK_accounts_keystore_Import(ksHandle, exportedPrivKeyJSON, (char*)newPassphrase, (char*)passphrase, &err);
        if (importedFromExtKsJSON == NULL) {
            fprintf(stderr, "Failed to import exported private key into keystore: %s\n", err ? err : "unknown error");
            if (err) {
                GoWSK_FreeCString(err);
                err = NULL;
            }
        } else {
            printf("Successfully imported private key from extkeystore into keystore: %s\n", importedFromExtKsJSON);
            GoWSK_FreeCString(importedFromExtKsJSON);
        }
        GoWSK_FreeCString(exportedPrivKeyJSON);
    } else {
        fprintf(stderr, "Skipping import test - no exported private key available\n");
    }
    
    // Test 13: List accounts
    printf("\n12. Listing accounts...\n");
    err = NULL; // Reset error pointer
    char* ksAccounts = GoWSK_accounts_keystore_Accounts(ksHandle, &err);
    if (ksAccounts == NULL) {
        fprintf(stderr, "Failed to list keystore accounts: %s\n", err ? err : "unknown error");
        if (err) {
            GoWSK_FreeCString(err);
            err = NULL;
        }
    } else {
        printf("Keystore accounts: %s\n", ksAccounts);
        GoWSK_FreeCString(ksAccounts);
    }
    
    err = NULL; // Reset error pointer
    char* extKsAccounts = GoWSK_accounts_extkeystore_Accounts(extKsHandle, &err);
    if (extKsAccounts == NULL) {
        fprintf(stderr, "Failed to list extkeystore accounts: %s\n", err ? err : "unknown error");
        if (err) {
            GoWSK_FreeCString(err);
            err = NULL;
        }
    } else {
        printf("ExtKeystore accounts: %s\n", extKsAccounts);
        GoWSK_FreeCString(extKsAccounts);
    }
    
    // Test 14: Unlock and sign
    printf("\n14. Testing unlock and sign...\n");
    err = NULL; // Reset error pointer
    GoWSK_accounts_keystore_Unlock(ksHandle, importedAddress, (char*)passphrase, &err);
    if (err != NULL) {
        fprintf(stderr, "Failed to unlock keystore account: %s\n", err);
        GoWSK_FreeCString(err);
        err = NULL;
    } else {
        printf("Keystore account unlocked\n");
        
        // Sign a test hash
        const char* testHash = "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef";
        err = NULL; // Reset error pointer
        char* signature = GoWSK_accounts_keystore_SignHash(ksHandle, importedAddress, (char*)testHash, &err);
        if (signature == NULL) {
            fprintf(stderr, "Failed to sign hash: %s\n", err ? err : "unknown error");
            if (err) {
                GoWSK_FreeCString(err);
                err = NULL;
            }
        } else {
            printf("Signature: %s\n", signature);
            GoWSK_FreeCString(signature);
        }
        
        err = NULL; // Reset error pointer
        GoWSK_accounts_keystore_Lock(ksHandle, importedAddress, &err);
        if (err != NULL) {
            fprintf(stderr, "Failed to lock keystore account: %s\n", err);
            GoWSK_FreeCString(err);
            err = NULL;
        } else {
            printf("Keystore account locked\n");
        }
    }
    
    // Test 15: Derive child account in extkeystore
    printf("\n15. Deriving child account in extkeystore...\n");
    const char* childPath = "m/44'/60'/0'/0/1";
    err = NULL; // Reset error pointer
    char* childAccountJSON = GoWSK_accounts_extkeystore_DeriveWithPassphrase(
        extKsHandle, extImportedAddress, (char*)childPath, 0, (char*)passphrase, NULL, &err);
    if (childAccountJSON == NULL) {
        fprintf(stderr, "Failed to derive child account: %s\n", err ? err : "unknown error");
        if (err) {
            GoWSK_FreeCString(err);
            err = NULL;
        }
    } else {
        printf("Child account: %s\n", childAccountJSON);
        GoWSK_FreeCString(childAccountJSON);
    }
    
    // Cleanup
    printf("\n16. Cleaning up...\n");
    GoWSK_FreeCString(mnemonic);
    GoWSK_FreeCString(extKeyStr);
    GoWSK_FreeCString(derivedKeyStr);
    GoWSK_FreeCString(privateKeyHex);
    GoWSK_FreeCString(address);
    GoWSK_FreeCString(ksAccount1JSON);
    GoWSK_FreeCString(extKsAccount1JSON);
    GoWSK_FreeCString(ksAccount2JSON);
    GoWSK_FreeCString(extKsAccount2JSON);
    free(importedAddress);
    free(extImportedAddress);
    GoWSK_accounts_keystore_CloseKeyStore(ksHandle);
    GoWSK_accounts_extkeystore_CloseKeyStore(extKsHandle);
    
    printf("\n=== Accounts test completed successfully ===\n");
    return 0;
}