#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Header generated by Go build -buildmode=c-shared
#include "libgowalletsdk.h"

int main(int argc, char** argv) {
    const char* url = "https://ethereum-rpc.publicnode.com";
    const char* addr = "0x0000000000000000000000000000000000000000";

    char* err = NULL;
    unsigned long long h = GoWSK_NewClient((char*)url, &err);
    if (h == 0) {
        fprintf(stderr, "Failed to create client: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        return 1;
    }

    char* chain = GoWSK_ChainID(h, &err);
    if (chain == NULL) {
        fprintf(stderr, "ChainID error: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_CloseClient(h);
        return 1;
    }
    printf("ChainID: %s\n", chain);
    GoWSK_FreeCString(chain);

    char* balance = GoWSK_GetBalance(h, (char*)addr, &err);
    if (balance == NULL) {
        fprintf(stderr, "GetBalance error: %s\n", err ? err : "unknown error");
        if (err) GoWSK_FreeCString(err);
        GoWSK_CloseClient(h);
        return 1;
    }
    printf("Balance(wei): %s\n", balance);
    GoWSK_FreeCString(balance);

    GoWSK_CloseClient(h);
    return 0;
}
