// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/status-im/go-wallet-sdk/pkg/gas (interfaces: GasClient,FeeModelResolver,BlockInclusionEstimator)
//
// Generated by this command:
//
//	mockgen -destination=mock/ethclient.go . GasClient,FeeModelResolver,BlockInclusionEstimator
//

// Package mock_gas is a generated GoMock package.
package mock_gas

import (
	context "context"
	big "math/big"
	reflect "reflect"

	ethereum "github.com/ethereum/go-ethereum"
	ethclient "github.com/status-im/go-wallet-sdk/pkg/ethclient"
	gomock "go.uber.org/mock/gomock"
)

// MockGasClient is a mock of GasClient interface.
type MockGasClient struct {
	ctrl     *gomock.Controller
	recorder *MockGasClientMockRecorder
	isgomock struct{}
}

// MockGasClientMockRecorder is the mock recorder for MockGasClient.
type MockGasClientMockRecorder struct {
	mock *MockGasClient
}

// NewMockGasClient creates a new mock instance.
func NewMockGasClient(ctrl *gomock.Controller) *MockGasClient {
	mock := &MockGasClient{ctrl: ctrl}
	mock.recorder = &MockGasClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGasClient) EXPECT() *MockGasClientMockRecorder {
	return m.recorder
}

// BlockNumber mocks base method.
func (m *MockGasClient) BlockNumber(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockNumber indicates an expected call of BlockNumber.
func (mr *MockGasClientMockRecorder) BlockNumber(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockNumber", reflect.TypeOf((*MockGasClient)(nil).BlockNumber), ctx)
}

// EstimateGas mocks base method.
func (m *MockGasClient) EstimateGas(ctx context.Context, msg ethereum.CallMsg) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateGas", ctx, msg)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateGas indicates an expected call of EstimateGas.
func (mr *MockGasClientMockRecorder) EstimateGas(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateGas", reflect.TypeOf((*MockGasClient)(nil).EstimateGas), ctx, msg)
}

// EthGetBlockByNumberWithFullTxs mocks base method.
func (m *MockGasClient) EthGetBlockByNumberWithFullTxs(ctx context.Context, number *big.Int) (*ethclient.BlockWithFullTxs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthGetBlockByNumberWithFullTxs", ctx, number)
	ret0, _ := ret[0].(*ethclient.BlockWithFullTxs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EthGetBlockByNumberWithFullTxs indicates an expected call of EthGetBlockByNumberWithFullTxs.
func (mr *MockGasClientMockRecorder) EthGetBlockByNumberWithFullTxs(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthGetBlockByNumberWithFullTxs", reflect.TypeOf((*MockGasClient)(nil).EthGetBlockByNumberWithFullTxs), ctx, number)
}

// FeeHistory mocks base method.
func (m *MockGasClient) FeeHistory(ctx context.Context, blockCount uint64, lastBlock *big.Int, rewardPercentiles []float64) (*ethereum.FeeHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeHistory", ctx, blockCount, lastBlock, rewardPercentiles)
	ret0, _ := ret[0].(*ethereum.FeeHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeeHistory indicates an expected call of FeeHistory.
func (mr *MockGasClientMockRecorder) FeeHistory(ctx, blockCount, lastBlock, rewardPercentiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeHistory", reflect.TypeOf((*MockGasClient)(nil).FeeHistory), ctx, blockCount, lastBlock, rewardPercentiles)
}

// LineaEstimateGas mocks base method.
func (m *MockGasClient) LineaEstimateGas(ctx context.Context, msg ethereum.CallMsg) (*ethclient.LineaEstimateGasResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LineaEstimateGas", ctx, msg)
	ret0, _ := ret[0].(*ethclient.LineaEstimateGasResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LineaEstimateGas indicates an expected call of LineaEstimateGas.
func (mr *MockGasClientMockRecorder) LineaEstimateGas(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LineaEstimateGas", reflect.TypeOf((*MockGasClient)(nil).LineaEstimateGas), ctx, msg)
}

// SuggestGasPrice mocks base method.
func (m *MockGasClient) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestGasPrice", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestGasPrice indicates an expected call of SuggestGasPrice.
func (mr *MockGasClientMockRecorder) SuggestGasPrice(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestGasPrice", reflect.TypeOf((*MockGasClient)(nil).SuggestGasPrice), ctx)
}

// MockFeeModelResolver is a mock of FeeModelResolver interface.
type MockFeeModelResolver struct {
	ctrl     *gomock.Controller
	recorder *MockFeeModelResolverMockRecorder
	isgomock struct{}
}

// MockFeeModelResolverMockRecorder is the mock recorder for MockFeeModelResolver.
type MockFeeModelResolverMockRecorder struct {
	mock *MockFeeModelResolver
}

// NewMockFeeModelResolver creates a new mock instance.
func NewMockFeeModelResolver(ctrl *gomock.Controller) *MockFeeModelResolver {
	mock := &MockFeeModelResolver{ctrl: ctrl}
	mock.recorder = &MockFeeModelResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeeModelResolver) EXPECT() *MockFeeModelResolverMockRecorder {
	return m.recorder
}

// BlockNumber mocks base method.
func (m *MockFeeModelResolver) BlockNumber(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockNumber indicates an expected call of BlockNumber.
func (mr *MockFeeModelResolverMockRecorder) BlockNumber(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockNumber", reflect.TypeOf((*MockFeeModelResolver)(nil).BlockNumber), ctx)
}

// EthGetBlockByNumberWithFullTxs mocks base method.
func (m *MockFeeModelResolver) EthGetBlockByNumberWithFullTxs(ctx context.Context, number *big.Int) (*ethclient.BlockWithFullTxs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthGetBlockByNumberWithFullTxs", ctx, number)
	ret0, _ := ret[0].(*ethclient.BlockWithFullTxs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EthGetBlockByNumberWithFullTxs indicates an expected call of EthGetBlockByNumberWithFullTxs.
func (mr *MockFeeModelResolverMockRecorder) EthGetBlockByNumberWithFullTxs(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthGetBlockByNumberWithFullTxs", reflect.TypeOf((*MockFeeModelResolver)(nil).EthGetBlockByNumberWithFullTxs), ctx, number)
}

// FeeHistory mocks base method.
func (m *MockFeeModelResolver) FeeHistory(ctx context.Context, blockCount uint64, lastBlock *big.Int, rewardPercentiles []float64) (*ethereum.FeeHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeHistory", ctx, blockCount, lastBlock, rewardPercentiles)
	ret0, _ := ret[0].(*ethereum.FeeHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeeHistory indicates an expected call of FeeHistory.
func (mr *MockFeeModelResolverMockRecorder) FeeHistory(ctx, blockCount, lastBlock, rewardPercentiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeHistory", reflect.TypeOf((*MockFeeModelResolver)(nil).FeeHistory), ctx, blockCount, lastBlock, rewardPercentiles)
}

// SuggestGasTipCap mocks base method.
func (m *MockFeeModelResolver) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestGasTipCap", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestGasTipCap indicates an expected call of SuggestGasTipCap.
func (mr *MockFeeModelResolverMockRecorder) SuggestGasTipCap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestGasTipCap", reflect.TypeOf((*MockFeeModelResolver)(nil).SuggestGasTipCap), ctx)
}

// MockBlockInclusionEstimator is a mock of BlockInclusionEstimator interface.
type MockBlockInclusionEstimator struct {
	ctrl     *gomock.Controller
	recorder *MockBlockInclusionEstimatorMockRecorder
	isgomock struct{}
}

// MockBlockInclusionEstimatorMockRecorder is the mock recorder for MockBlockInclusionEstimator.
type MockBlockInclusionEstimatorMockRecorder struct {
	mock *MockBlockInclusionEstimator
}

// NewMockBlockInclusionEstimator creates a new mock instance.
func NewMockBlockInclusionEstimator(ctrl *gomock.Controller) *MockBlockInclusionEstimator {
	mock := &MockBlockInclusionEstimator{ctrl: ctrl}
	mock.recorder = &MockBlockInclusionEstimatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockInclusionEstimator) EXPECT() *MockBlockInclusionEstimatorMockRecorder {
	return m.recorder
}

// BlockNumber mocks base method.
func (m *MockBlockInclusionEstimator) BlockNumber(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockNumber indicates an expected call of BlockNumber.
func (mr *MockBlockInclusionEstimatorMockRecorder) BlockNumber(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockNumber", reflect.TypeOf((*MockBlockInclusionEstimator)(nil).BlockNumber), ctx)
}

// EthGetBlockByNumberWithFullTxs mocks base method.
func (m *MockBlockInclusionEstimator) EthGetBlockByNumberWithFullTxs(ctx context.Context, number *big.Int) (*ethclient.BlockWithFullTxs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EthGetBlockByNumberWithFullTxs", ctx, number)
	ret0, _ := ret[0].(*ethclient.BlockWithFullTxs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EthGetBlockByNumberWithFullTxs indicates an expected call of EthGetBlockByNumberWithFullTxs.
func (mr *MockBlockInclusionEstimatorMockRecorder) EthGetBlockByNumberWithFullTxs(ctx, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EthGetBlockByNumberWithFullTxs", reflect.TypeOf((*MockBlockInclusionEstimator)(nil).EthGetBlockByNumberWithFullTxs), ctx, number)
}

// FeeHistory mocks base method.
func (m *MockBlockInclusionEstimator) FeeHistory(ctx context.Context, blockCount uint64, lastBlock *big.Int, rewardPercentiles []float64) (*ethereum.FeeHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeeHistory", ctx, blockCount, lastBlock, rewardPercentiles)
	ret0, _ := ret[0].(*ethereum.FeeHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeeHistory indicates an expected call of FeeHistory.
func (mr *MockBlockInclusionEstimatorMockRecorder) FeeHistory(ctx, blockCount, lastBlock, rewardPercentiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeeHistory", reflect.TypeOf((*MockBlockInclusionEstimator)(nil).FeeHistory), ctx, blockCount, lastBlock, rewardPercentiles)
}
